# Generated by Django 5.0.3 on 2024-03-09 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_rename_category_product_categories"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="categories",
            new_name="category",
        ),
    ]
